name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - published

jobs:
  build-and-publish:
    name: Build and publish release
    runs-on: ubuntu-latest
    if: ${{ secrets.PYPI_API_TOKEN != '' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_NON_INTERACTIVE: '1'
        run: python -m twine upload dist/*
